### ISSUE TITLE
Add cargo.lock

### ISSUE THREAD

**Issue by dbrgn** [meh/screenruster#4]
As this is a binary project, you should check in `Cargo.lock` into Git.

When I compile the code (with current nightly), I get an error message: #3

This is probably because a dependency has been updated, but you didn't notice because your Cargo locks the version dependencies. You can simulate this by running `cargo update` (but you probably know that already).

By adding the Cargo.lock, everyone's code will compile the same way (with regard to dependencies) as it does on your machine.

**Comment by meh** [comment]
I'd rather not check in the `Cargo.lock`, I prefer to know if things are breaking with dependencies and I didn't notice.

#3 is actually me forgetting to push changes to `main.rs`, the change was local.

**Comment by wucke13** [comment]
@meh
I'd rather prefer having `Cargo.lock`.

1. According to official documentation, it should be there for binaries ( https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html )
2. For packaging this in the `nixpkgs`, a `Cargo.lock` is needed. I would prefer to not patch the src's with my own `Cargo.lock` in favor of having one provided by the code maintainer.
3. Regarding the "know if things are breaking", you may be satisfied with `cargo update --dry-run`?

**Comment by meh** [comment]
That's fair, adding it :panda_face:
